In [27]:
import torch

device = "cpu"

A= torch.tensor([[1, 2, 4],
                 [1, 3, 9],
                 [1, 4, 16]], device=device)
a= torch.tensor([0.9, 0, 0, 0], device=device)
b= torch.tensor([0, 0.3, 0.3, 0.3], device=device)
#0.9, 0, 0, 0
#0, 0.3, 0.3, 0.3
a= a[:, None]
b= b[None, :]
print(a*b)
print(a)
print(b)

tensor([[0.0000, 0.2700, 0.2700, 0.2700],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])
tensor([[0.9000],
        [0.0000],
        [0.0000],
        [0.0000]])
tensor([[0.0000, 0.3000, 0.3000, 0.3000]])
